### ISSUE TITLE
11

### ISSUE THREAD

**Issue by Zol12** [Kaivosukeltaja/php-indefinite-article#5]
Hi!

Thank you for making this little code. It's great!
However I noticed it has problems with some terms starting with numbers, like there is a brand called "11 Degrees".
The code outputs "a 11 Degrees".

Can you please have a look on that?

**Comment by Kaivosukeltaja** [comment]
Hi and thanks for the feedback! Been a while since I've touched this repository but certainly this needs to be fixed. :) I'm assuming that the expected output would be "11 Degrees" without any article whatsoever? Same with any words that have a number followed with a word, such as "7 seconds", "1 love", "99 problems" and "0 ideas"?

**Comment by Zol12** [comment]
It should be pronounced like "an eleven degress t-shirt". How can we add this and other exceptions to the code?

**Comment by Kaivosukeltaja** [comment]
It looks like we should touch line 64. It's checking how many digits there are after "11" or "18" so that:
- 18 = an eighteen
- 181 = a one-hundred and eighty one
- 18000 = an eighteen-thousand

However, it only filters out any spaces, commas and decimals but it also counts any letters as digits. As a result, "11 Degrees" turns into "11Degrees" which has 9 characters so it's treated as an "a" word.

Possible solution would be amending the parameter list on that row to also include any non-digits. I can do it myself some time but a PR would also be heartily welcomed.

**Comment by David263** [comment]
"Eleven" is obviously an "an" word. If the algorithm doesn't handle it, it's a bug. Make sure it fails then report it as a bug.

**Comment by Zol12** [comment]
Sorry, but I don't know how can I report it as a bug.

**Comment by Kaivosukeltaja** [comment]
This is now fixed, thanks for the report!

**Comment by Zol12** [comment]
Thank you! Works great!
